### ISSUE TITLE
Add database connection

### ISSUE THREAD

**Issue by yeekim96** [uts-ios-dev/uts-ios-2019-project3-group-181#8]

**Comment by yeekim96** [comment]
Going to use a local/internal database - Probably SQLite or Realm

**Comment by Jeremychan113** [comment]
What about just Base64 it & save into coredata?

**Comment by yeekim96** [comment]
> What about just Base64 it & save into coredata?

Well @LukeChalkley seems to have figured out how to get Realm working, so we might just use that. Personally not entirely sure though since I haven't really looked into the database/tableview stuff.

**Comment by Jeremychan113** [comment]
Maybe a bit of an overkill to use Realm for this, but up to you guys, just looking to make it easier for everyone

**Comment by yeekim96** [comment]
Yeah I'm not sure, but Luke seemed to have had it figured out when I talked to him yesterday
